/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class FileSet {
  constructor(patterns: Array<string>)
  get paths(): Array<string>
  hash(): HashStream
}

/**
 * This type implements JavaScript's async iterable protocol.
 * It can be used with `for await...of` loops.
 *
 * @see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols#the_async_iterator_and_async_iterable_protocols
 */
export declare class HashStream {
  [Symbol.asyncIterator](): AsyncGenerator<Progress, void, undefined>
}

export interface Failed {
  hashed: false
  path: string
  total: number
  succeeded: number
  failed: number
  error: string
}

export interface Hashed {
  hashed: true
  path: string
  total: number
  succeeded: number
  failed: number
  hash: string
  duration: number
}

export type Progress =
  Hashed | Failed
