/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class FileSet {
  constructor(patterns: Array<string>)
  get paths(): Array<string>
  hash(): HashStream
}

/**
 * This type implements JavaScript's async iterable protocol.
 * It can be used with `for await...of` loops.
 *
 * @see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols#the_async_iterator_and_async_iterable_protocols
 */
export declare class HashStream {
  [Symbol.asyncIterator](): AsyncGenerator<HashResult | HashError, void, undefined>
}

export interface HashError {
  path: string
  error: string
}

export interface HashResult {
  path: string
  hash: string
  duration: number
}
